# Generated by Django 5.1.6 on 2025-02-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
    ]
